apiVersion: v1
kind: Service
metadata:
  name: {{ include "squid-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "squid-proxy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "squid-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.squid.port }}
      protocol: TCP
